/**
 * Deterministic test data constants used across all E2E test suites.
 *
 * IDs are generated by the API (PGlite UUIDs / nanoid) at runtime —
 * we rely on names and emails for lookup, not hardcoded IDs.
 */

export const TEST_USER = {
  email: "test@vsync.dev",
  password: "testpassword123",
  name: "Test User",
} as const;

export const TEST_ORG = {
  name: "Test Org",
  slug: "test-org",
} as const;

export const TEST_WORKFLOWS = {
  simpleFetch: { name: "Simple Fetch Workflow" },
  codeTest: { name: "Code Test Workflow" },
} as const;

/** Second user for multi-user tests (e.g. member invitation). */
export const SECOND_USER = {
  email: "second@vsync.dev",
  password: "secondpassword123",
  name: "Second User",
} as const;

/** Run status values matching the RunStatus type from @vsync/shared-types. */
export const RUN_STATUSES = [
  "pending",
  "running",
  "completed",
  "failed",
  "cancelled",
  "awaiting_action",
] as const;

/** WebSocket event types for live run updates. */
export const WS_EVENTS = {
  connected: "connected",
  runStarted: "run:started",
  runStep: "run:step",
  runCompleted: "run:completed",
  runFailed: "run:failed",
  runAwaitingAction: "run:awaiting_action",
} as const;
