import type {
  Block,
  BlockType,
  Step,
  WorkflowContext,
  WorkflowVersion,
  RunStatus,
} from "@vsync/shared-types";

/* ── Interpreter configuration ──────────────────────────── */

/**
 * Static interpreter settings injected at construction time.
 * Controls execution limits and deferred-execution parallelism.
 */
export interface InterpreterConfig {
  /** Maximum number of steps before the engine force-stops a run */
  maxSteps: number;

  /** Maximum wall-clock time (ms) before the engine aborts */
  maxDurationMs: number;

  /**
   * Concurrent deferred iterations allowed per goto block.
   * Acts as a semaphore to prevent runaway parallelism.
   */
  deferConcurrency: number;
}

/* ── Per-run configuration ──────────────────────────────── */

/**
 * Options passed when starting or resuming a run.
 * Combines identity, trigger data, and the workflow snapshot.
 */
export interface RunConfig {
  /** Unique run identifier — generated by the caller */
  runId: string;

  /** Organization owning this run */
  orgId: string;

  /** Device or agent that is executing */
  deviceId: string;

  /** Workflow version snapshot to execute */
  workflowVersion: WorkflowVersion;

  /** Trigger event payload */
  event: Record<string, unknown>;

  /** Pre-seeded state — e.g. from a previous partial run */
  initialState?: Record<string, unknown>;

  /** Pre-seeded secrets — decrypted at run start */
  secrets?: Record<string, string>;

  /** Named filesystem paths for the target platform */
  paths?: Record<string, string>;

  /** Optional key resolver for $keys.* expressions */
  keyResolver?: (key: string) => unknown;
}

/* ── Block execution result ─────────────────────────────── */

/**
 * The shape every block handler must return.
 * Deltas are merged into the workflow context after each step.
 */
export interface BlockResult {
  /** Key-value pairs to merge into workflow state */
  stateDelta?: Record<string, unknown>;

  /** Key-value pairs to merge into ephemeral cache */
  cacheDelta?: Record<string, unknown>;

  /** Artifact references produced by this block */
  artifactsDelta?: Record<string, unknown>;

  /** Events emitted during execution */
  eventDelta?: Record<string, unknown>;
}

/* ── Block handler ──────────────────────────────────────── */

/**
 * Function signature for a registered block handler.
 * The engine calls this with the block's logic and context,
 * and expects a BlockResult (or void for side-effect-only blocks).
 */
export type BlockHandler = (
  block: Block,
  context: WorkflowContext,
) => Promise<BlockResult | void>;

/* ── Run result ─────────────────────────────────────────── */

/**
 * Final outcome returned by executeRun / resumeRun.
 * Contains the terminal status, all recorded steps, and the
 * final context snapshot for inspection.
 */
export interface RunResult {
  /** Terminal status of the run */
  status: RunStatus;

  /** Ordered list of every step executed (or skipped) */
  steps: Step[];

  /** Final workflow context after all blocks have run */
  context: WorkflowContext;

  /** Error message if the run failed */
  errorMessage?: string;

  /** Wall-clock duration in milliseconds */
  durationMs: number;
}

/* ── Error handling strategy ────────────────────────────── */

/**
 * Per-block error handling configuration.
 * 'continue' logs the error and moves to the next block.
 * 'abort' halts the entire run immediately.
 */
export type ErrorStrategy = "continue" | "abort";
